package ExceptionHandling

fun main(args: Array<String>) {

    // There are four different keywords used in exception handling. These are:
    //
    // *try   ->  try block contains set of statements which might generate an exception. It must be followed by either catch or finally or both.
    // *catch   ->  catch block is used to catch the exception thrown from try block.
    // *finally   ->  finally block always execute whether exception is handled or not. So it is used to execute important code statement.
    // *throw   ->  throw keyword is used to throw an exception explicitly.

}